@echo off
echo deleting build folders...
rd /s /q build
rd /s /q build-android32
rd /s /q build-android64
echo Building for Windows...
geode build
echo Building for Android32...
geode build -p android32
echo Building for Android64...
geode build -p android64
echo Finished building